# Generated by Django 5.2.14 on 2026-05-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["-release_year"]},
        ),
        migrations.RemoveField(
            model_name="movie",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="original_title",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="overview",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="poster_url",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="release_date",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="movie",
            name="release_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="kp_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="tmdb_id",
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
