# Generated by Django 5.2.14 on 2026-06-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_movie_options_remove_movie_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="tmdb_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
