# Generated by Django 6.0.5 on 2026-05-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('directors', models.JSONField(blank=True, default=list)),
                ('actors', models.JSONField(blank=True, default=list)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('kp_rating', models.FloatField(blank=True, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('content_vector', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
