# Generated by Django 5.2.14 on 2026-05-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={},
        ),
        migrations.AlterModelOptions(
            name="roomvote",
            options={},
        ),
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
