# Generated by Django 5.2.14 on 2026-05-27 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_alter_room_options_alter_roomvote_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Комната",
                "verbose_name_plural": "Комнаты",
            },
        ),
        migrations.AlterModelOptions(
            name="roomvote",
            options={"verbose_name": "Голос", "verbose_name_plural": "Голоса"},
        ),
        migrations.AddField(
            model_name="room",
            name="invite_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="room",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="room",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="joined_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
