# Generated by Django 5.2.14 on 2026-06-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_alter_room_options_alter_roomvote_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="max_duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Максимальная длительность фильма (минуты)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="mood_genre",
            field=models.CharField(
                blank=True,
                help_text="Общий жанр настроения комнаты",
                max_length=50,
                null=True,
            ),
        ),
    ]
