# Generated by Django 5.2.14 on 2026-06-06 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0004_room_max_duration_room_mood_genre"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="max_duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="mood_genre",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="RoomMemberSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mood_genres",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список выбранных жанров настроения",
                    ),
                ),
                (
                    "max_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Максимальная длительность фильма (минуты)",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_settings",
                        to="rooms.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки участника",
                "verbose_name_plural": "Настройки участников",
                "ordering": ["user__username"],
                "unique_together": {("room", "user")},
            },
        ),
    ]
